server:
  #port: 8002
  port: ${PORT:${SERVER_PORT:0}}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      #hostname: localhost
      instance-id: $spring.application.name}:${}spring.application.instance_id:${random.value}}

resilience4j.circuitbreaker:
  instances:
    usuariosCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10
    allCB:
      registerHealthIndicator: true
      slidingWindowSize: 10
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: TIME_BASED
      minimumNumberOfCalls: 4
      waitDurationInOpenState: 5s
      failureRateThreshold: 50
      eventConsumerBufferSize: 10

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ldap_izzi_empleados?useSSL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
    username: root
    password: c3_7f-iqQos3
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
  hibernate:
    ddl-auto: update