server:
  port: 8003

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rh_ssorhh_izzi?useSSL=false&serverTimezone=UTC&useLegacyDateTimeCode=false
    username: root
    password: c3_7f-iqQos3
    driver-class-name: org.hibernate.dialect.MySQL8Dialect

  jpa:
    show-sql: true
  hibernate:
    ddl-auto: update  