server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker
          uri: https://github.com/JACUMA6/izzi_ssorhh_ldap
          search-paths: config-data
  application:
    name: config-service